fixtures:
  repositories:
    "apt": "https://github.com/puppetlabs/puppetlabs-apt"
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "v2.2.1"
  symlinks:
    "opsmatic": "#{source_dir}"
